name: Deploy to Cloud Run

on:
  push:
    branches: [main]  # or your primary branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode service account key and save to file
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $HOME/gcp-key.json

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image to Google Container Registry
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/ai-business-assistant
          gcloud builds submit --tag $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/ai-business-assistant
          gcloud run deploy ai-business-assistant \
            --image $IMAGE \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}